server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts_db
    username: ${POSTGRES_USER:lab}
    password: ${POSTGRES_PASSWORD:lab}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: dummy
        secret-key: dummy
      s3:
        bucket: melimbank-bucket
      sqs:
        transactions-queue: melimbank-transactions
management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    probes:
      enabled: true