server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers_db
    username: ${POSTGRES_USER:lab}
    password: ${POSTGRES_PASSWORD:lab}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    probes:
      enabled: true
